image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/cmdline-tools/latest/bin
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
  - echo y | sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null 2>&1
  - echo y | sdkmanager "platform-tools" >/dev/null 2>&1
  - echo y | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null 2>&1
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/apk/release/app-release-unsigned.apk
    expire_in: 1 week
